//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDS_TITLE                       1
#define IDS_VERSION                     2
#define IDS_USAGE                       3
#define IDS_CONFIG_SETTING              4
#define IDS_OPTION_PROFILE              7
#define IDS_OPTION_OUTDIR               8
#define IDS_OPTION_OUTPUTDIR            8
#define IDS_OPTION_CONTAINER            9
#define IDS_OPTION_GROUP_CONTAINER      10
#define IDS_OPTION_INPUTDIR             11
#define IDS_OPTION_VERBOSE              15
#define IDS_OPTION_LDIFFILE             16
#define IDS_OPTION_BASEDN               17
#define IDS_OPTION_INIFILE              18
#define IDS_OPTION_SERVER               19
#define IDS_OPTION_XMLCONFIG            20
#define IDS_OPTION_FORM_LIST            21
#define IDS_OPTION_LOGFILE              22
#define IDS_OPTION_FILENAME             23
#define IDS_OPTION_LOGFILE_APPEND       24
#define IDS_OPT_ERR_ILLEGAL_OPTION      100
#define IDS_OPT_ERR_NOHANDLER           101
#define IDS_OPT_ERR_MISSEDARG           102
#define IDR_SCHEMA                      104
#define IDS_ERR_INIT_FAILED             110
#define IDS_ERR_FILE_OPEN               111
#define IDS_ERR_NOTES                   112
#define IDS_ERR_OUTLOOK                 112
#define IDS_ERR_NO_PERSONS_FOUND        113
#define IDS_ERR_OUTLINE_NOTE_NOT_FOUND  114
#define IDS_ERR_OUTLINE_ITEM_NOT_FOUND  115
#define IDS_ERR_DIR_NOT_CREATED1        116
#define IDS_ERR_DIR_NOT_CREATED2        117
#define IDS_ERR_DIR_NOT_CREATED3        118
#define IDS_ERR_VIEW_NOT_FOUND          119
#define IDS_ERR_SMTP_NO_DELIM           120
#define IDS_ERR_FILE_NOT_CREATED2       122
#define IDR_OUTLOOK_2003                143
#define GSS_LOGO                        153
#define IDS_PROFILE_NOTOPEN             173
#define IDS_FOLDER_NOTCREATED           174
#define IDS_EXIT_CODE                   200
#define IDS_ENTER_METHOD                201
#define IDS_EXIT_METHOD                 202
#define IDS_PROCESSING_CHOICE           203
#define IDS_MAIL_FILE                   204
#define IDS_SWITCHING_ID                205
#define IDS_ENTER_PWD                   206
#define IDS_NOTE_SKIPPED_NOT_MEMO       207
#define IDS_NOTE_SKIPPED_NOT_REQUIRED_FORM 207
#define IDS_NOTE_SKIPPED_NOT_REQUIRED_DATERANGE 208
#define IDS_NOTE_FORM                   210
#define IDS_NOTE_FORM_FIELD_NOTFOUND    211
#define IDS_SMTP_NAME_FOR_LOOKUP        214
#define IDS_SMTP_NAME_SUBSTITUTED       215
#define IDS_SMTP_NAME_UNRESOLVED        216
#define IDS_SMTP_NAME_ADDTOUNRESOLVED   217
#define IDS_LOG_MAPI_FOLDER_CREATED     265
#define IDS_LOG_MSGEMPTY_CREATED        268
#define IDS_LOG_MSGEMPTY_NOTCREATED     269
#define IDS_LOG_MAPI_STORETBLFAIL       270
#define IDS_LOG_MAPI_QUERYROWFAIL       271
#define IDS_LOG_MAPI_NODEFAULTSTORE     272
#define IDS_LOG_MAPI_OPENSTOREFAIL      273
#define IDS_LOG_MAPI_OPENSTOREWARN      274
#define IDS_LOG_MAPI_STOREOPENED        275
#define IDS_LOG_MAPI_RECIP_TO           276
#define IDS_LOG_MAPI_ATTACH             277
#define IDS_LOG_MAPI_PROFILECR          278
#define IDS_LOG_MAPI_LOGOFF             279
#define IDS_LOG_MAPI_FOLDERDELETED      280
#define IDS_LOG_MAPI_RECIP_CC           281
#define IDS_LOG_MAPI_RECIP_BCC          282
#define IDS_LOG_MAPI_FROM               283
#define IDS_LOG_MAPI_FROM_NAME          283
#define IDS_LOG_MAPI_IMP_HIGH           284
#define IDS_LOG_MAPI_MSG_SAVEFAILED     285
#define IDS_LOG_MAPI_FROM_EMAIL         286
#define IDS_LOG_MAPI_FOLDER_NOTCREATED  287
#define IDS_LOG_MAPI_FOLDER_NOTOPENED   288
#define IDS_LOG_MAPI_PSTMASK            289
#define IDS_LOG_MAPI_PROFILECHECK       290
#define IDS_LOG_MAPI_PROFILENOTFOUND    291
#define IDS_LOG_MAPI_PROFILEDELETED     292
#define IDS_LOG_MAPI_PROFILEDELETEERR   293
#define IDS_LOG_MAPI_PROFILECREATEERR   294
#define IDS_LOG_MAPI_FROM_ADDRTYPE      295
#define IDS_LOG_MAPI_CALENDAR_ERR       295
#define IDS_LOG_MAPI_MSG_SAVED          296
#define IDS_LOG_CONV_START              300
#define IDS_LOG_CONV_END                301
#define IDS_LOG_EXEC_PATH               302
#define IDS_LOG_EXEC_VERSION            303
#define IDS_LOG_FOLDER_ID_NUMBER        304
#define IDS_LOG_NOTE_ID_NUMBER          305
#define IDS_LOG_INCORRECT_AFTER_BEFORE  306
#define IDS_LOG_SMTPADR_SKIP            307
#define IDS_LOG_SMTPADR_IGNOREEMPTY     308
#define IDS_LOG_TEXT_FIELD_PROBLEM      309
#define IDS_LOG_EXIT_CODE               310
#define IDS_LOG_LOCAL_NSFFILE           311
#define IDS_LOG_LOCAL_PSTFILE           311
#define IDS_LOG_FIND_HANDLE_OPEN        312
#define IDS_LOG_FIND_HANDLE_CLOSE       313
#define IDS_LOG_FIND_HANDLE_FILE        314
#define IDS_LOG_MAPI_OPENSTORE          315
#define IDS_LOG_MAPI_INIT               316
#define IDS_LOG_MAPI_OPENFOLDER         317
#define IDS_LOG_MAPI_DELETEOUTBOX       318
#define IDS_LOG_FULLMASK                318
#define IDS_LOG_NOTES_CLOSEFILE         319
#define IDS_LOG_MAPI_CANT_GET_ID        319
#define IDS_LOG_NOTES_MAILFILE          400
#define IDS_LOG_TOTAL_MSGS              401
#define IDS_LOG_TOTAL_MSGS_DONE         402
#define IDS_LOG_TOTAL_ATTACH_DONE       403
#define IDS_LOG_TOTAL_MSGS_FILE         404
#define IDS_LOG_TOTAL_MSGS_FILE_DONE    405
#define IDS_LOG_TOTAL_MSGS_SKIPPED      406
#define IDS_LOG_TOTAL_MSGS_FILE_SKIPPED 407
#define IDS_LOG_TOTAL_MSGS_ERROR        408
#define IDS_LOG_TOTAL_MSGS_FILE_ERROR   409
#define IDS_LOG_TOTAL_MSGS_NOFORM       410
#define IDS_LOG_TOTAL_MSGS_FILE_NOFORM  411
#define IDS_LOG_TOTAL_FILES_DONE        412
#define IDS_LOG_TOTAL_FILES_ERROR       413
#define IDS_LOG_TOTAL_MSGS_FILE_REPLCONFLICT 414
#define IDS_LOG_CONT_PART               415
#define IDS_LOG_BODY_PART_SIZE          416
#define IDS_LOG_MASK_STR                417
#define IDS_LOG_TOTAL_MSGS_ENCRYPT      418
#define IDS_LOG_SMTP_LOOKUP_CHECKING    418
#define IDS_LOG_TOTAL_MSGS_FILE_ENCRYPTED 419

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
