// external success code
#define MIGRATION_SUCCESS	0
#define MIGRATION_SUCCESS_SOME_ERRORS			MIGRATION_SUCCESS + 1

// internally used
#define MIGRATION_PARAMETERS_OK				101
#define MIGRATION_STEP_SUCCESS				102

// possible external return codes
#define MIGRATION_ERR_BASE					MIGRATION_SUCCESS_SOME_ERRORS
#define MIGRATION_ERR_NO_PARAMETERS			MIGRATION_ERR_BASE + 1
#define MIGRATION_ERR_MISSEDARG				MIGRATION_ERR_BASE + 2
#define MIGRATION_ERR_ILLEGAL_OPTION		MIGRATION_ERR_BASE + 3
#define MIGRATION_ERR_NO_OPTION_HANDLER		MIGRATION_ERR_BASE + 4

#define MIGRATION_ERR_FAILED				MIGRATION_ERR_BASE + 10
#define MIGRATION_ERR_INIT_FAILED			MIGRATION_ERR_BASE + 11